# .github/workflows/semgrep-scan-latest-release.yml
name: Weekly Semgrep Security Scan on Latest Release

on:
  schedule:
    - cron: '0 7 * * 0'  # Runs at 7am UTC every Sunday
  workflow_dispatch:  # Enables manual run from the Actions tab

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Determine latest release or fallback to main or master
      id: get_latest_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
        
        # Check if latest release exists
        if [[ "$latest_release" == "null" ]]; then
          echo "No release found. Checking for main branch."
          
          # Check if main branch exists
          if git ls-remote --heads origin main &>/dev/null; then
            latest_release="main"
          elif git ls-remote --heads origin master &>/dev/null; then
            # If main doesn't exist, fallback to master
            echo "No main branch found. Defaulting to master branch."
            latest_release="master"
          else
            echo "No release, main, or master branch found. Exiting..."
            exit 1
          fi
        fi
        
        echo "latest_release=$latest_release" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.latest_release }}

    - name: Set up Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash

    - name: Cache Semgrep
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Semgrep
      run: |
        source venv/bin/activate
        pip install --upgrade semgrep
      shell: bash

    - name: Run Semgrep scan
      run: |
        source venv/bin/activate
        semgrep --config=p/ci --json --output=semgrep-results.json
      shell: bash

    - name: Generate summary report
      run: |
        echo "## Semgrep Scan Summary" >> $GITHUB_STEP_SUM
